name: Acorn
on:
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 

    - name: Setup Acorn
      uses: acorn-io/actions-setup@v2
      with:
        acorn-version: main

    - name: Login Acorn to ghcr.io
      uses: acorn-io/actions-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build/Push Acorn
      run: acorn build --push -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

    - name: Build/Push Acorn as latest
      run: acorn build --push -t ghcr.io/${{ github.repository }}:latest .
